project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Regression Analysis with R"
  author: 
    - "Sophie Lee"
    - "Dean Marchiori"
  downloads: [pdf]  
  search: true
  navbar:
    right: 
      - icon: github
        href: https://github.com/deanmarchiori/regression_course
        aria-label: Github
  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - chapters/02_pre_regression.qmd
    - chapters/03_linear_reg.qmd
    - chapters/04_glm.qmd
    - chapters/05_discussion.qmd
  appendices: 
    - chapters/data_description.qmd
    - chapters/exercise_solutions.qmd
    - chapters/ols.qmd
    - chapters/setup.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf: 
    theme: scrbook